### ISSUE TITLE
最后怎么使用呢？

### ISSUE THREAD

**Issue by whhxmwhh** [shell-script/v2ray-heroku#1]
我的app出现的web界面是这样的：
![default](https://user-images.githubusercontent.com/7959854/44827192-a6bda480-ac44-11e8-8d23-20bd39b76ae4.JPG)

**Comment by 1715173329** [comment]
请提供更准确的数据，比如您在部署时输入的相关信息。
如果您是使用默认配置直接部署，请直接告知appname即可。
